---
- hosts: base
  vars_files:
    - vars/main.yml
    - vars/private.yml

  tasks:
    - include_tasks: tasks/base/mk_files-dir.yml
    - include_tasks: tasks/base/mk_dnsmasq-conf.yml
    - include_tasks: tasks/base/mk_libvirtd-conf.yml
    - include_tasks: tasks/base/mk_nginx-conf.yml
    - include_tasks: tasks/base/mk_boot-ipxe-cfg.yml
    - include_tasks: tasks/base/mk_ocp-install-config.yml
    - include_tasks: tasks/base/get_materials.yml

- hosts: kvm_host
  vars_files:
    - vars/main.yml
    - vars/private.yml

  tasks:
    - include_tasks: tasks/kvm_host/send_materials.yml
