---
- name: install the latest version of libvirt, dnsmasq and nginx
  dnf:
    name:
      - libvirt-client
      - libvirt-daemon
      - virt-install
      - dnsmasq
      - nginx
      - python3-lxml
      - python3-libselinux
      - python3-policycoreutils
    state: latest
