---
- name: start libvirt daemon
  service:
    name: libvirtd
    state: started

- name: check if openshift nat already exists
  virt_net:
    command: list_nets
  register: all_nets

- name: destroy old openshift nat
  virt_net:
    command: destroy
    name: openshift
  when: "'openshift' in all_nets.list_nets"

- name: undefine old openshift nat
  virt_net:
    command: undefine
    name: openshift
  when: "'openshift' in all_nets.list_nets"

- name: define openshift nat
  virt_net:
    command: define
    name: openshift
    xml: "{{lookup('file', 'files/{{ openshift.version }}/conf/libvirtd.nat-openshift.xml')}}"

- name: start openshift nat
  virt_net:
    command: create
    name: openshift
    state: active
