---
- name: allow nginx(http_port_t) to listen on extra tcp ports
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
      - "6443"
      - "8000"
      - "22623"

- name: set seboolean flag on and keep it persistent across reboots
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
    ignore_selinux_state: yes
  with_items:
      - "httpd_can_network_connect"
      - "httpd_graceful_shutdown"
      - "httpd_can_network_relay"
      - "nis_enabled"
      - "daemons_dump_core"
