---
# want fix: FCOS has a different checksum provision method
#           and cannot be handled by the same logic as RHCOS.
- name: download coreos kernel
  get_url:
    url: "{{ url.coreos_kernel_url }}"
    dest: "files/{{ openshift.install_version }}/dependencies/{{ config.coreos_kernel }}"
    #checksum: "sha256:{{ url.sha256_dep_url }}"
  register: downloaded_kernel
  until: downloaded_kernel is succeeded
  retries: 3

- name: download coreos initramfs
  get_url:
    url: "{{ url.coreos_initramfs_url }}"
    dest: "files/{{ openshift.install_version }}/dependencies/{{ config.coreos_initramfs }}"
    #checksum: "sha256:{{ url.sha256_dep_url }}"
  register: downloaded_initramfs
  until: downloaded_initramfs is succeeded
  retries: 3

- name: download coreos bios
  get_url:
    url: "{{ url.coreos_bios_url }}"
    dest: "files/{{ openshift.install_version }}/dependencies/{{ config.coreos_bios }}"
    #checksum: "sha256:{{ url.sha256_dep_url }}"
  register: downloaded_bios
  until: downloaded_bios is succeeded
  retries: 3

- name: download coreos bios signature
  get_url:
    url: "{{ url.coreos_bios_url }}.sig"
    dest: "files/{{ openshift.install_version }}/dependencies/{{ config.coreos_bios }}.sig"
    #checksum: "sha256:{{ url.sha256_dep_url }}"
  register: downloaded_bios_sig
  until: downloaded_bios_sig is succeeded
  retries: 3
  when: openshift.dist == "okd"

- name: download openshift installer
  get_url:
    url: "{{ url.openshift_installer_url }}"
    dest: "files/{{ openshift.install_version }}/clients/{{ config.openshift_installer }}"
    checksum: "sha256:{{ url.sha256_client_url }}"
  register: downloaded_installer
  until: downloaded_installer is succeeded
  retries: 3

- name: download openshift client
  get_url:
    url: "{{ url.openshift_client_url }}"
    dest: "files/{{ openshift.install_version }}/clients/{{ config.openshift_client }}"
    checksum: "sha256:{{ url.sha256_client_url }}"
  register: downloaded_client
  until: downloaded_client is succeeded
  retries: 3

