---
- name: make ipxe/boot.ipxe.ROLE
  template:
    src:  templates/ipxe/boot-ipxe-cfg.j2
    dest: "files/{{ openshift.version }}/conf/boot.ipxe.{{ item }}"
  with_items:
    - bootstrap
    - master
    - worker
