---
- name: make files dir
  file:
    path: "files/{{ openshift.install_version }}"
    state: directory

- name: make files/clients dir
  file:
    path: "files/{{ openshift.install_version }}/clients"
    state: directory

- name: make files/dependencies dir
  file:
    path: "files/{{ openshift.install_version }}/dependencies"
    state: directory

- name: make files/conf dir
  file:
    path: "files/{{ openshift.install_version }}/conf"
    state: directory
